name: transly_ai
description: "Transly AI — bilingual AI-powered translation app (Arabic / English)."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.11.5

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # State management
  flutter_bloc: ^9.1.1

  # DI
  get_it: ^8.0.3

  # Navigation
  go_router: ^15.1.2

  # Networking
  dio: ^5.8.0+1

  # ML Kit — translation
  google_mlkit_translation: ^0.12.0

  # Speech
  flutter_tts: ^4.2.2

  # Connectivity
  connectivity_plus: ^6.1.4

  # Fonts
  google_fonts: ^6.2.1

  # Utils
  intl: ^0.20.2

  cupertino_icons: ^1.0.8
  pretty_dio_logger: ^1.4.0
  firebase_core: ^4.13.0
  shared_preferences: ^2.5.5
  flutter_secure_storage: ^11.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  fake_async: ^1.3.3

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/images/
